version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always   
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productivity
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
